---
- name: AWS CLI query version
  ansible.builtin.command: aws --version
  failed_when: false
  changed_when: false
  register: aws_cli_version

- name: Download and extract installer
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip
    dest: /opt
    remote_src: true
  become: true

- name: Install AWS CLI
  ansible.builtin.command: /opt/aws/install
  become: true
  when: aws_cli_version.rc != 0

- name: Verify AWS CLI version
  ansible.builtin.command: aws --version
  changed_when: false

# allows checking AWS SDK versions
- name: pip install python packages
  ansible.builtin.pip:
    name:
      - packaging
      - boto3
    state: latest
  become: true