---
- name: Create directory .aws/
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory

- name: Append AWS credentials
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.aws/credentials"
    block: |
      [default]
      aws_access_key_id = {{ aws_access_key }}
      aws_secret_access_key = {{ aws_secret_key }}
    create: yes